/loadout/new_player
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/feet/socks/ankle,
		/obj/item/clothing/feet/socks/ankle,
		/obj/item/clothing/pants/normal/grey,
		/obj/item/clothing/shirt/normal/grey,
		/obj/item/clothing/feet/shoes/colored/black,
		/obj/item/clothing/feet/shoes/colored/black/left,
		/obj/item/clothing/back/storage/satchel/loadout/new_player,
		/obj/item/clothing/ears/headset
	)

/loadout/new_player/female
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/panty,
		/obj/item/clothing/undertop/underwear/bra,
		/obj/item/clothing/feet/socks/knee/white,
		/obj/item/clothing/feet/socks/knee/white,
		/obj/item/clothing/pants/skirt/grey,
		/obj/item/clothing/shirt/normal/grey,
		/obj/item/clothing/feet/shoes/colored/black,
		/obj/item/clothing/feet/shoes/colored/black/left,
		/obj/item/clothing/back/storage/satchel/loadout/new_player,
		/obj/item/clothing/ears/headset
	)

/loadout/nt/player_crusader
	spawning_items = list(
		/obj/item/clothing/uniform/miner,
		/obj/item/clothing/overwear/armor/knight/red,
		/obj/item/clothing/neck/cape/hunter,
		/obj/item/clothing/head/helmet/knight/red,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/back/storage/dufflebag/syndicate/ammo,
		/obj/item/storage/pouch/single/black,
		/obj/item/storage/pouch/single/black,
		/obj/item/weapon/melee/energy/plightbringer,
		/obj/item/weapon/ranged/magic/staff/blackflame,
		/obj/item/weapon/melee/shield/glass,
		/obj/item/soulgem/common,
		/obj/item/soulgem/common,
		/obj/item/soulgem/common,
		/obj/item/soulgem/common,
		/obj/item/soulgem/common,
		/obj/item/container/syringe/medipen/bicaridine
	)

/loadout/nt/player_penetrator
	spawning_items = list(
		/obj/item/clothing/shirt/suit/pinstripe,
		/obj/item/clothing/pants/normal/black,
		/obj/item/clothing/head/hat/warden/drill,
		/obj/item/clothing/glasses/thermal,
		/obj/item/clothing/overwear/armor/molded_armor/security,
		/obj/item/clothing/hands/gloves/colored/blue,
		/obj/item/clothing/hands/gloves/colored/blue/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/storage/pouch/double/black,
		/obj/item/storage/pouch/double/black,
		/obj/item/weapon/ranged/energy/rifle/hardlight/equipped,
		/obj/item/weapon/melee/energy/grazer,
		/obj/item/powercell/industrial,
		/obj/item/weapon/melee/tool/crowbar,
		/obj/item/powercell/industrial,
		/obj/item/powercell/industrial,
		/obj/item/powercell/industrial,
		/obj/item/powercell/industrial,
		/obj/item/grenade/timed/explosive,
		/obj/item/grenade/timed/explosive,
		/obj/item/cell_charger
	)

/loadout/nt/shieldman
	spawning_items = list(
		/obj/item/clothing/uniform/miner,
		/obj/item/clothing/glasses/nightvision,
		/obj/item/clothing/overwear/armor/space_military,
		/obj/item/clothing/head/helmet/security/old,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/back/storage/dufflebag/syndicate/ammo,
		/obj/item/weapon/ranged/energy/freezegun,
		/obj/item/storage/pouch/double/black,
		/obj/item/storage/pouch/double/black,
		/obj/item/weapon/ranged/bullet/magazine/pistol/tactical/mod,
		/obj/item/weapon/melee/shield/ballistic,
		/obj/item/powercell/industrial,
		/obj/item/powercell/industrial,
		/obj/item/magazine/pistol_45,
		/obj/item/magazine/pistol_45,
		/obj/item/magazine/pistol_45,
		/obj/item/container/syringe/medipen/epinephrine,
		/obj/item/container/medicine/trauma_kit,
		/obj/item/weapon/melee/tool/crowbar,
	)

/loadout/nt/lightwizard
	spawning_items = list(
		/obj/item/clothing/shirt/normal/reinforced,
		/obj/item/clothing/pants/normal/reinforced,
		/obj/item/clothing/overwear/armor/knight/battlemage,
		/obj/item/clothing/head/helmet/knight/battlemage,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/weapon/melee/staff_of_healing,
		/obj/item/clothing/back/wings/angel,
		/obj/item/storage/pouch/double/black,
		/obj/item/storage/pouch/double/black,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/magic/tome/frost,
		/obj/item/weapon/ranged/magic/tome/fireball,
		/obj/item/container/beaker/bottle/mana_potion,
		/obj/item/container/beaker/bottle/mana_potion,
		/obj/item/container/beaker/bottle/mana_potion
	)

/loadout/nt/sledge
	spawning_items = list(
		/obj/item/clothing/uniform/miner,
		/obj/item/clothing/glasses/nightvision,
		/obj/item/clothing/overwear/armor/slavticool,
		/obj/item/clothing/mask/gas/mining,
		/obj/item/clothing/head/helmet/security/tactical/advanced,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/back/storage/dufflebag/syndicate/ammo,
		/obj/item/weapon/melee/mace/,
		/obj/item/weapon/ranged/bullet/revolver/grenade_launcher,
		/obj/item/storage/ammo/grenade_40mm,
		/obj/item/storage/ammo/grenade_40mm,
		/obj/item/grenade/timed/explosive,
		/obj/item/grenade/timed/explosive,
		/obj/item/grenade/timed/explosive,
		/obj/item/container/syringe/medipen/bicaridine
	)

/loadout/nt/cowboy
	spawning_items = list(
		/obj/item/clothing/uniform/hos,
		/obj/item/clothing/neck/cloak/black,
		/obj/item/clothing/overwear/armor/bulletproof,
		/obj/item/clothing/overwear/coat/brown,
		/obj/item/clothing/head/hat/warden/drill,
		/obj/item/weapon/melee/shield,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/storage/pouch/single/black,
		/obj/item/storage/pouch/single/black,
		/obj/item/weapon/ranged/bullet/magazine/pistol/dynamic,
		/obj/item/magazine/dynamic_50,
		/obj/item/magazine/dynamic_50,
		/obj/item/magazine/dynamic_50,
		/obj/item/magazine/dynamic_50,
		/obj/item/magazine/dynamic_50,
		/obj/item/grenade/timed/explosive,
		/obj/item/grenade/timed/explosive,
		/obj/item/handcuffs
	)

/loadout/nt/halo/odst
	spawning_items = list(
		/obj/item/clothing/uniform/halo/odst,
		/obj/item/clothing/ears/headset,
		/obj/item/clothing/hands/gloves/colored/combat,
		/obj/item/clothing/hands/gloves/colored/combat/left,
		/obj/item/clothing/feet/shoes/carbon_boot,
		/obj/item/clothing/feet/shoes/carbon_boot/left,
		/obj/item/clothing/belt/storage/colored/black
	)

/loadout/nt/halo/odst/cqb
	spawning_items = list(
		/obj/item/clothing/overwear/hardsuit/halo/odst/cqb,
		/obj/item/clothing/head/helmet/hardsuit/halo/odst/cqb,
		/obj/item/clothing/back/storage/backpack/halo/odst/cqb,
		/obj/item/weapon/melee/sword/machete,
		/obj/item/weapon/ranged/bullet/magazine/smg/halo/m7,
		/obj/item/weapon/ranged/bullet/magazine/smg/halo/m7,
		/obj/item/weapon/ranged/bullet/magazine/shotgun/halo/kv32,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/kv32,
		/obj/item/magazine/halo/kv32,
		/obj/item/magazine/halo/kv32,
		/obj/item/magazine/halo/kv32,
		/obj/item/container/syringe/medipen/bicaridine,
		/obj/item/container/syringe/medipen/kelotane
	)

/loadout/nt/halo/odst/medic
	spawning_items = list(
		/obj/item/clothing/overwear/hardsuit/halo/odst/medic,
		/obj/item/clothing/head/helmet/hardsuit/halo/odst/medic,
		/obj/item/clothing/back/storage/backpack/halo/odst/medic,
		/obj/item/weapon/ranged/bullet/pump/shotgun/halo/m90,
		/obj/item/weapon/ranged/bullet/magazine/pistol/halo/socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/container/blood_pack/full/o_negative,
		/obj/item/container/blood_pack/full/o_negative,
		/obj/item/container/blood_pack/full/o_negative,
		/obj/item/storage/ammo/buckshot,
		/obj/item/storage/ammo/buckshot,
		/obj/item/defib,
		/obj/item/container/syringe/medipen/epinephrine,
		/obj/item/container/syringe/medipen/epinephrine,
		/obj/item/container/syringe/medipen/bicaridine,
		/obj/item/container/syringe/medipen/kelotane,
		/obj/item/container/syringe/medipen/iron,
		/obj/item/storage/kit/advanced/filled,
		/obj/item/clothing/belt/storage/medical/filled
	)

/loadout/halo/unsc_soldier
	spawning_items = list(
		/obj/item/clothing/uniform/halo/marine,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/head/helmet/halo/marine,
		/obj/item/clothing/overwear/armor/halo/marine,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/storage/pouch/triple/black,
		/obj/item/storage/pouch/triple/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/weapon/ranged/bullet/magazine/pistol/halo/socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/weapon/melee/sword/machete
	)

/loadout/nt/halo/odst/commander
	spawning_items = list(
		/obj/item/clothing/uniform/halo/odst,
		/obj/item/clothing/ears/headset,
		/obj/item/clothing/hands/gloves/colored/combat,
		/obj/item/clothing/hands/gloves/colored/combat/left,
		/obj/item/clothing/feet/shoes/carbon_boot,
		/obj/item/clothing/feet/shoes/carbon_boot/left,
		/obj/item/clothing/head/helmet/hardsuit/halo/odst/commander,
		/obj/item/clothing/overwear/hardsuit/halo/odst/commander,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/melee/sword/sabre
	)

/loadout/nt/halo/odst/rifleman
	spawning_items = list(
		/obj/item/clothing/overwear/hardsuit/halo/odst,
		/obj/item/clothing/head/helmet/hardsuit/halo/odst,
		/obj/item/clothing/back/storage/backpack/halo/odst,
		/obj/item/weapon/ranged/bullet/magazine/rifle/halo/ma5b,
		/obj/item/weapon/ranged/bullet/magazine/pistol/halo/socom,
		/obj/item/weapon/melee/sword/machete,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/grenade/timed/explosive/halo,
		/obj/item/grenade/timed/explosive/halo,
		/obj/item/container/syringe/medipen/bicaridine,
		/obj/item/container/syringe/medipen/kelotane
	)

/loadout/nt/halo/odst/sl
	spawning_items = list(
		/obj/item/clothing/overwear/hardsuit/halo/odst/leader,
		/obj/item/clothing/head/helmet/hardsuit/halo/odst/leader,
		/obj/item/clothing/back/storage/backpack/halo/odst/sl,
		/obj/item/weapon/ranged/bullet/magazine/rifle/halo/br55,
		/obj/item/weapon/ranged/bullet/magazine/smg/halo/m7,
		/obj/item/weapon/melee/sword/machete,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/m7,
		/obj/item/magazine/halo/br55,
		/obj/item/magazine/halo/br55,
		/obj/item/magazine/halo/br55,
		/obj/item/magazine/halo/br55,
		/obj/item/grenade/timed/explosive/halo,
		/obj/item/halo/mortar,
		/obj/item/supply_remote/crates/ammunition,
		/obj/item/supply_remote/crates/ammunition,
		/obj/item/supply_remote/crates/ammunition,
		/obj/item/container/syringe/medipen/bicaridine,
		/obj/item/container/syringe/medipen/kelotane
	)

/loadout/nt/halo/odst/engineer
	spawning_items = list(
		/obj/item/clothing/overwear/hardsuit/halo/odst/engineer,
		/obj/item/clothing/head/helmet/hardsuit/halo/odst/engineer,
		/obj/item/clothing/back/storage/backpack/halo/odst/engineer,
		/obj/item/clothing/belt/storage/tool/filled,
		/obj/item/weapon/ranged/bullet/magazine/rifle/halo/ma5b,
		/obj/item/weapon/ranged/bullet/magazine/pistol/halo/socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/magnum_socom,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/magazine/halo/ma5b,
		/obj/item/grenade/landmine/proximity/explosive/halo,
		/obj/item/grenade/landmine/proximity/explosive/halo,
		/obj/item/magazine/minigun_46,
		/obj/item/magazine/minigun_46,
		/obj/item/magazine/minigun_46,
		/obj/item/magazine/minigun_46,
		/obj/item/powercell/industrial,
		/obj/item/powercell/industrial,
		/obj/item/deployable/mob/sentry,
		/obj/item/deployable/mob/sentry,
		/obj/item/deployable/barricade/filled,
		/obj/item/container/syringe/medipen/bicaridine,
		/obj/item/container/syringe/medipen/kelotane
	)

/loadout/nt/halo/odst/sharpshooter
	spawning_items = list(
		/obj/item/clothing/overwear/hardsuit/halo/odst/sharp,
		/obj/item/clothing/head/helmet/hardsuit/halo/odst/sharp,
		/obj/item/clothing/back/storage/backpack/halo/odst/sharp,
		/obj/item/weapon/ranged/bullet/magazine/rifle/halo/srs,
		/obj/item/weapon/ranged/bullet/revolver/halo/m41,
		/obj/item/magazine/halo/srs,
		/obj/item/magazine/halo/srs/ap,
		/obj/item/magazine/halo/srs/ap,
		/obj/item/magazine/halo/srs,
		/obj/item/magazine/halo/srs,
		/obj/item/magazine/halo/srs,
		/obj/item/magazine/halo/srs,
		/obj/item/bullet_cartridge/halo/spnkr,
		/obj/item/bullet_cartridge/halo/spnkr,
		/obj/item/container/syringe/medipen/bicaridine,
		/obj/item/container/syringe/medipen/kelotane
	)

/loadout/nt/halo/covenant/unggoyminor
	spawning_items = list(
		/obj/item/clothing/uniform/halo/covenant/unggoy,
		/obj/item/clothing/overwear/armor/halo/covenant/unggoy,
		/obj/item/clothing/mask/gas/halo/unggoy,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/energy/halo/cov_pistol,
		/obj/item/powercell/advanced,
		/obj/item/powercell/advanced,
		/obj/item/powercell/advanced
	)